### ISSUE TITLE
extension cannot be started. TypeError: Cannot read properties of undefined (reading 'loc')

### ISSUE THREAD

**Issue by dhenfie** [deakjahn/vscode-php-allfactor#2]
Hi. i want to report that this extension is not working on my vscode.
the error message i get is
'TypeError: Cannot read properties of undefined (reading 'loc')'

![Screenshot from 2023-03-17 20-20-51](https://user-images.githubusercontent.com/45891576/225920225-00bfc106-8524-42fe-a42e-d82be0a85ba4.png)

## additional information
OS Ubuntu 22.10 (Kinetic Kudu)
Visual Studio Code Version 1.76.2

**Comment by deakjahn** [comment]
I would need to see some PHP source code that triggers this error. Do you think you can come up with a minimal sample that causes it?

**Comment by dhenfie** [comment]
I don't know. i haven't written any php code yet.

**Comment by deakjahn** [comment]
Considering that the plugin is a PHP refactoring plugin, that would be the first step to do. :-) But it's possible that an empty source file leads to this error, I'll check it out. If it is so, it's a completely harmless warning then (but should be suppressed, anyway).

As you can see from the log, the extension _has been started_ all right, and it actually runs, just that it emits some errors during the analysis of the current file.
