### ISSUE TITLE
Add possibility to exclude directories

### ISSUE THREAD

**Issue by AndreiOrmanji** [deakjahn/vscode-php-allfactor#3]
**Description:**

I've faced the issue when extension can not be started because of lack of permissions:
![image](https://user-images.githubusercontent.com/48985454/229721366-11227912-7c4a-4a3b-bd9d-52f880e09e7d.png)

It will be nice to have a possibility to exclude some directories by patterns from analysis as it is for intelephense.

**Comment by deakjahn** [comment]
Do you think it should be added as a setting, or just silently fail on those folders?

**Comment by deakjahn** [comment]
@AndreiOrmanji Wait a minute... The error mesage was incorrect in some cases, the extension did start, it just silently ignored the problem. It also depended on whether it was an inaccesible folder or a file. Anyway, I published a new 1.3.3 version for now that has no error messages and let's return to the issue if necessary.

**Comment by AndreiOrmanji** [comment]
> Do you think it should be added as a setting, or just silently fail on those folders?

It would be nice to have it as a setting(with 3 levels as it is in vscode (user, remote, workspace). It should be useful for evading such errors and possibly will improve overall performance, because it will decrease the amount of scanned/watched files and directories

**Comment by AndreiOrmanji** [comment]
I dont know if error from screenshot is related to the current one, but here it is:
![image](https://user-images.githubusercontent.com/48985454/230558451-497088a0-3590-4eab-8e47-2bd83ef5faab.png)

**Comment by deakjahn** [comment]
@AndreiOrmanji Not related, `[Doc]` clearly signals some problems with a PhpDoc block comment. Hard to tell without actually seeing it... But you can easily get such errors if the actual PHP source isn't syntactically correct (generally or temporarily), this doesn't mean any real problem.

**Comment by AndreiOrmanji** [comment]
> It would be nice to have it as a setting(with 3 levels as it is in vscode (user, remote, workspace). It should be useful for evading such errors and possibly will improve overall performance, because it will decrease the amount of scanned/watched files and directories

Ok.
What is about to add a setting for defining exclude files/dirs patterns?

**Comment by deakjahn** [comment]
OK, I'll look into it.

**Comment by deakjahn** [comment]
@AndreiOrmanji Version 1.3.4.

**Comment by AndreiOrmanji** [comment]
thank you
