### ISSUE TITLE
Items in menu of extracting a constant is duplicated

### ISSUE THREAD

**Issue by AndreiOrmanji** [deakjahn/vscode-php-allfactor#4]
![image](https://user-images.githubusercontent.com/48985454/230558916-186c31b5-02d7-4ba9-8def-2deb5832d283.png)

**Comment by deakjahn** [comment]
That's actually misguiding. There are in fact two enclosing blocks there, an inner one and an outer one (at least this is the only way I can reproduce it). The question is whether we list all enclosing blocks, and if so, how to diferentiate them.

**Comment by AndreiOrmanji** [comment]
> That's actually misguiding. There are in fact two enclosing blocks there, an inner one and an outer one (at least this is the only way I can reproduce it). The question is whether we list all enclosing blocks, and if so, how to diferentiate them.

Is it possible to show preview as for `Rename` ?
If it is so, then you could use it to show how selecting each of variants will affect existing code.

**Comment by deakjahn** [comment]
Unfortunately, not. VS Code itself shows the preview, not the extension.

**Comment by deakjahn** [comment]
@AndreiOrmanji I'll experiment with adding a specifier in parentheses.

**Comment by deakjahn** [comment]
It will soon appear in the upcoming version 1.3.4. Thanks.
